(ai4db) root@145efaf89057:/code/AI4QueryOptimizer/baseline/Lero/lero/test_script# python test.py --query_path q_test_0_merge.txt --output_query_latency_file q_test_2_merge.test
Read 22 test queries.
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/e348a37a91d2ee90c1fb779307dbaa02/cbc88b3688f5210dddd4fe66677d4d16
get the history file: ./log/query_latency/e348a37a91d2ee90c1fb779307dbaa02/cbc88b3688f5210dddd4fe66677d4d16
1728737193.4813783 q21 0.288
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
Error q20
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    do_run_query(q, fp, ["SET enable_lero TO True"], args.output_query_latency_file, True, None, None)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 123, in do_run_query
    _, plan_json = run_query("EXPLAIN (COSTS FALSE, FORMAT JSON, SUMMARY) " + sql, run_args)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 28, in run_query
    cur.execute(q)
psycopg2.errors.InternalError_: fail to get score from Lero

connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/45ad09986c24ca6cc81026607b6979a8/87a312276757a532803cc50ef7f3e068
get the history file: ./log/query_latency/45ad09986c24ca6cc81026607b6979a8/87a312276757a532803cc50ef7f3e068
1728737193.6264517 q22 134.41
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
Error q18
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    do_run_query(q, fp, ["SET enable_lero TO True"], args.output_query_latency_file, True, None, None)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 123, in do_run_query
    _, plan_json = run_query("EXPLAIN (COSTS FALSE, FORMAT JSON, SUMMARY) " + sql, run_args)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 28, in run_query
    cur.execute(q)
psycopg2.errors.InternalError_: fail to get score from Lero

connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/113fcfe8e2c000c1fae1faa212fc6140/4af0e6e31ca19afa61f249fe2dcf64d0
get the history file: ./log/query_latency/113fcfe8e2c000c1fae1faa212fc6140/4af0e6e31ca19afa61f249fe2dcf64d0
1728737193.7125683 q19 60.659
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/e047ada2329073f8409ba77d0dfefbe2/de98c6243e2131c940a9ba2c815e9d40
get the history file: ./log/query_latency/e047ada2329073f8409ba77d0dfefbe2/de98c6243e2131c940a9ba2c815e9d40
1728737193.777823 q4 2657.864
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/8a4b512452b843bb4b6803706ee94499/016561ec1995970770411661b501f6aa
get the history file: ./log/query_latency/8a4b512452b843bb4b6803706ee94499/016561ec1995970770411661b501f6aa
1728737193.9976573 q5 11.1
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/7aef7012d11645664336f1e2e30756e9/e247a1564f19c38b8fabd18120601133
get the history file: ./log/query_latency/7aef7012d11645664336f1e2e30756e9/e247a1564f19c38b8fabd18120601133
1728737194.193355 q7 0.143
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
Error q6
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    do_run_query(q, fp, ["SET enable_lero TO True"], args.output_query_latency_file, True, None, None)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 123, in do_run_query
    _, plan_json = run_query("EXPLAIN (COSTS FALSE, FORMAT JSON, SUMMARY) " + sql, run_args)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 28, in run_query
    cur.execute(q)
psycopg2.errors.InternalError_: fail to init Lero

connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/da8c087cc9127b55832192e6bf01ddb6/a58e896b4c6be737c7925bd0bf107377
get the history file: ./log/query_latency/da8c087cc9127b55832192e6bf01ddb6/a58e896b4c6be737c7925bd0bf107377
1728737194.3754709 q2 63.217
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/322fa39d5773b8fd7a9093a717bbf9ea/92425325ec20fdd3411297ce7b5fc599
get the history file: ./log/query_latency/322fa39d5773b8fd7a9093a717bbf9ea/92425325ec20fdd3411297ce7b5fc599
1728737194.4615498 q3 50.371
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
Error q1
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    do_run_query(q, fp, ["SET enable_lero TO True"], args.output_query_latency_file, True, None, None)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 123, in do_run_query
    _, plan_json = run_query("EXPLAIN (COSTS FALSE, FORMAT JSON, SUMMARY) " + sql, run_args)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 28, in run_query
    cur.execute(q)
psycopg2.errors.InternalError_: fail to init Lero

connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/314edcfc045036f9820a2c28059e70cf/d6fcdc01749bbfa35ffa60a38d099b8f
get the history file: ./log/query_latency/314edcfc045036f9820a2c28059e70cf/d6fcdc01749bbfa35ffa60a38d099b8f
1728737194.6903086 q8 0.15
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/5ca4587a9e2351cd01bfabddfaf61c9c/472a7238783dcad02b00631fdd5f7bf9
get the history file: ./log/query_latency/5ca4587a9e2351cd01bfabddfaf61c9c/472a7238783dcad02b00631fdd5f7bf9
1728737194.8994195 q9 573.203
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/0b6980fa371c6152c8d2b1de22fd683b/673663f8414989c781278d0904817c17
get the history file: ./log/query_latency/0b6980fa371c6152c8d2b1de22fd683b/673663f8414989c781278d0904817c17
1728737194.9798014 q14 1279.548
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
Error q15
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    do_run_query(q, fp, ["SET enable_lero TO True"], args.output_query_latency_file, True, None, None)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 123, in do_run_query
    _, plan_json = run_query("EXPLAIN (COSTS FALSE, FORMAT JSON, SUMMARY) " + sql, run_args)
  File "/code/AI4QueryOptimizer/baseline/Lero/lero/test_script/utils.py", line 28, in run_query
    cur.execute(q)
psycopg2.errors.UndefinedTable: relation "revenue_test" does not exist
LINE 1: ... s_address, s_phone, total_revenue from supplier, revenue_te...
                                                             ^

connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/f68907db36fdc6079d213215a895c7fa/1970ab47c238a85c7de25256a553941a
get the history file: ./log/query_latency/f68907db36fdc6079d213215a895c7fa/1970ab47c238a85c7de25256a553941a
1728737195.078542 q17 55.848
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/24143dabf9f8241bdd37a82da92ff59c/e74b62b84cf323e118608bef3da5cd5a
get the history file: ./log/query_latency/24143dabf9f8241bdd37a82da92ff59c/e74b62b84cf323e118608bef3da5cd5a
1728737195.1641965 q16 406.165
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/15a2f292745f2fc49a5601d7b81b8812/784149df8fd1d21cf8f540f1b4b9e81d
get the history file: ./log/query_latency/15a2f292745f2fc49a5601d7b81b8812/784149df8fd1d21cf8f540f1b4b9e81d
1728737195.2334125 q12 1408.628
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/85e63a852d1dc56504fcb88d3e7c0c48/7702caacfd5f005960fd6a7c3b3fe397
get the history file: ./log/query_latency/85e63a852d1dc56504fcb88d3e7c0c48/7702caacfd5f005960fd6a7c3b3fe397
1728737195.299737 q13 1436.85
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/1aa377b84cc9b41bfcd42d8725633077/a738ff5fb015353b829b6f486e616493
get the history file: ./log/query_latency/1aa377b84cc9b41bfcd42d8725633077/a738ff5fb015353b829b6f486e616493
1728737195.397917 q11 0.145
connecting to db with  dbname=tpch2 user=postgres password=123 host=localhost port=5432
visit histroy path:  ./log/query_latency/4585a1f9a8084398410f5bb80c225b49/7dc85440529906c6da6704fba9bdf56c
get the history file: ./log/query_latency/4585a1f9a8084398410f5bb80c225b49/7dc85440529906c6da6704fba9bdf56c
1728737195.5122328 q10 742.672